### PR TITLE
ISSUE with socket listener

### PR DESCRIPTION
**Pull request by bpiselli**
It is not possible to change the value of the variable as it is not defined in the default

This is a major issue when you mount your environement with vagrant and want to change those to "vagrant" user and group

Moved 3 variables to the default folder

### CODE REVIEW

**Comment by drybjed** [comment]
Sounds good. Since `vars/main.yml` is empty, you can just remove the file entirely.

**Comment by mbarcia** [comment]
This is an improvement, but a better way to mount your PHP app is by running its own pool of threads (instead of using the default). The pool template of this role is fully customizable. Just saying.

**Comment by bpiselli** [comment]
Thanks for the very very fast answer !
Ok I will remove it completely

**Comment by bpiselli** [comment]
@mbarcia I customized the default pool but even then the pool file is created with "www-data" even if I change user and group inside it with "vagrant". 

Yes maybe we could use the same user/group in the pool conf (/templates/etc/php5/fpm/pool-available.d/pool.conf.j2) for "user/group" line 29/30 and for "listener" line53/54

What do you think ?

**Comment by drybjed** [comment]
Guys, just remember that owner and group of the socket are not the same that owner and group of the `php5-fpm` process. :-) Socket needs to be accessible by a webserver, and process needs to run with permissions of the user that maintains the application.

**Comment by mbarcia** [comment]
I think I never had trouble with the socket ownership, leaving the default values. Here is how I create a pool for a Drupal app: https://github.com/mbarcia/drupsible-deploy/blob/master/meta/main.yml#L45-L57

**Pull request merged**
